services:
  db:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: kotatsu_db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  server:
    extends:
      service: server
      file: docker-compose.common.yaml
    environment:
      DATABASE_DIALECT: mysql
    depends_on:
      - db

